# Site settings
title: Web Development Ninja
logo: /logo.png

permalink: /:categories/:slug

collections:
  tutorials:
    output: true

# Social settings
twitter:
  username: webdevelninja

facebook:
  publisher: 472349466295241

social:
  links:
    - https://github.com/webdevelopmentninja
    - https://twitter.com/webdevelopninja
    - https://facebook.com/Web-Development-Ninja-472349466295241/

# Google settings
google_tracking_id: UA-77924009-2
# google_ad_client: ca-pub-3538270718430385

gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
