# Site settings
title: Hash Array
tagline: Web Development, Game Development, Geekisms
logo: /logo.png

permalink: /:categories/:slug

collections:
  tutorials:
    output: true

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: tutorials
    values:
      layout: tutorial

# Social settings
disqus:
  shortname: hasharray

twitter:
  username: hasharray

facebook:
  publisher: 472349466295241

social:
  links:
    - https://github.com/hasharray
    - https://twitter.com/hasharray
    - https://facebook.com/hasharray

# Analytics settings
analytics_id: UA-83017016-1

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
