# Site settings
title: Web Development Ninja
permalink: /:categories/:slug

# Google settings
google_tracking_id: UA-77924009-2
# google_ad_client: ca-pub-3538270718430385

gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
