# Site settings
title: Hash Array
logo: /logo.png

permalink: /:categories/:slug

collections:
  tutorials:
    output: true

# Social settings
disqus:
  shortname: hasharray

twitter:
  username: hasharray

facebook:
  publisher: 472349466295241

social:
  links:
    - https://github.com/hasharray
    - https://twitter.com/hasharray
    - https://facebook.com/hasharray

# Google settings
google_tracking_id: UA-83017016-1
google_ad_client: ca-pub-3538270718430385

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
